title: Robert Winslow
author: Robert Winslow
remote_theme: RMWinslow/JTD-RMW
search_enabled: true
page_excerpts: true
gh_edit_link: false

compress_html:
  ignore:
    envs: all


plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  
whitelist:
  - jekyll-redirect-from
  
nav_external_links:
  - title: Just the Docs on GitHub
    url: https://github.com/just-the-docs/just-the-docs
  - title: CV
    url: rmwinslow.com/files/CV Robert Winslow.pdf
  - title: Blog
    url: blog.rmwinslow.com
