title: Robert Winslow
author: Robert Winslow
remote_theme: RMWinslow/JTD-RMW
search_enabled: true
page_excerpts: true
gh_edit_link: false
math: katex

compress_html:
  ignore:
    envs: all


plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  
whitelist:
  - jekyll-redirect-from
  
nav_external_links:
  - title: Blog
    url: https://blog.rmwinslow.com

