title: Robert Winslow
author: Robert Winslow
remote_theme: RMWinslow/just-the-docs-tweaked
search_enabled: true
page_excerpts: true
gh_edit_link: false

compress_html:
  ignore:
    envs: all


plugins:
  - jekyll-sitemap


collections:
  tests:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    tests:
      name: Tests
